#!/bin/bash
# This script is used to collect dynamic  profiling data for AMD GPUs using rocprof-compute and perform various analyses on the collected data.
echo "======================================================================================================"
if [ "$dry_run" = false ]; then
  # Enable all analyses when --analysis is omitted. Otherwise, use the analyses selected by the user.
  if [ -z "${analysis_arg:-}" ]; then
    enabled_analyses=("${valid_analyses[@]}")
  else
    parse_csv_list "${analysis_arg}" "analysis"
    enabled_analyses=("${parsed_csv_list[@]}")
  fi

  echo "Selected AMD analyses: $(join_by_comma "${enabled_analyses[@]}")"

  ##### Per-analysis metric requirements #### 
  # Build a de-duplicated list of metric IDs required by the enabled analyses.
  _metrics_set=()
  _add_metrics()
  {
    local metric

    for metric in "$@"; do
        if ! array_contains "$metric" "${_metrics_set[@]}"; then
            _metrics_set+=("$metric")
        fi
    done
  }

  # The IDs must match the fields parsed in parser_metrics.hpp
_metrics_register_spilling=(
    7.2.4   # Wavefront dependency wait cycles per cycle
    15.1.9  # Spill/stack instructions per kernel
    15.1.13 # Spill/stack processing cycles per kernel
    16.3.5  # VL1D cache line hit rate
    17.3.1  # Total incoming requests to L2 cache per kernel
)
_metrics_restrict=()
_metrics_vectorized_load=(
    7.2.4  # Wavefront dependency wait cycles per kernel
)
_metrics_atomic_instruction=(
    7.2.4   # Wavefront dependency wait cycles per kernel
    12.2.5  # LDS atomic return cycles per cycles
    16.3.3  # VL1D Cache Atomic Requests per kernel
    17.2.7  # Percentage of atomic write requests in write requests generated by the L2 cache to Infinity Fabric
    17.3.4  # L2 Cache Atomic Requests per kernel
    17.5.10 # Atomic requests towards Infinity Fabric per kernel
)
_metrics_wavefront_divergence=(
    10.1.6  # Branch instruction count per kernel
    11.2.5  # Branch unit utilization percentage
)
_metrics_shared_memory=(
    7.2.4   # Wavefront dependency wait cycles per kernel
    12.1.0  # Percentage of the kernel's execution time during which the LDS was actively processing operations, including loads, stores, atomics, and shuffle operations.
    12.1.1  # Percentage of CU cycles during which the schedulers issued LDS instructions, averaged across the SIMDs over the lifetime of the kernel.
    12.1.3  # Percentage of LDS service cycles spent resolving bank conflicts relative to the cycles required to serve the same accesses without bank conflicts.
)
_metrics_datatype_conversion=(
    10.2.14 # Type conversion instructions issued to the VALU per kernel
)
_metrics_deadlock_detection=()
_metrics_json_export=(
    7.2.4
    10.1.6
    10.2.14
    11.2.5
    12.1.0
    12.1.1
    12.1.3
    12.2.5
    15.1.9
    15.1.13
    16.3.3
    16.3.5
    17.2.7
    17.3.1
    17.3.4
    17.5.10
)

  for analysis in "${enabled_analyses[@]}"; do
    if ! array_contains "${analysis}" "${valid_analyses[@]}"; then
        echo "ERROR: Unknown analysis name in enabled_analyses: $analysis"
        exit 1
    fi

    array_name="_metrics_${analysis}"
    declare -n current_metrics="${array_name}"

    _add_metrics "${current_metrics[@]}"
  done

  if [ "$json" = true ]; then
    _add_metrics "${_metrics_json_export[@]}"
  fi

  amd_metrics_required=false
  if [ "${#_metrics_set[@]}" -gt 0 ]; then
    amd_metrics_required=true
  fi

  mkdir -p metrics
  if [ "$amd_metrics_required" = true ]; then
    echo "==== collecting kernel profiling data"
    start_metrics=$(date +%s.%N)
    # Filter required metrics mapped to hardware block for rocprof-compute profile 3.0.0 with -b option
    declare -A _metric_profile_block=(
        [7.2.4]="SQ"
        [10.1.6]="SQ"
        [10.2.14]="SQ"
        [11.2.5]="SQ"
        [12.1.0]="SQ"
        [12.1.1]="SQ"
        [12.1.3]="SQ"
        [12.2.5]="SQ"
        [15.1.9]="TA"
        [15.1.13]="TA"
        [16.3.3]="TCP"
        [16.3.5]="TCP"
        [17.2.7]="TCC"
        [17.3.1]="TCC"
        [17.3.4]="TCC"
        [17.5.10]="TCC"
    )

    _profile_blocks_set=()
    for metric_id in "${_metrics_set[@]}"; do
        block="${_metric_profile_block[$metric_id]:-}"

        if [ -z "$block" ]; then
            echo "ERROR: No AMD hardware block mapping for metric ID $metric_id"
            exit 1
        fi

        if ! array_contains "$block" "${_profile_blocks_set[@]}"; then
            _profile_blocks_set+=("$block")
        fi
    done

    profile_help=$(rocprof-compute profile --help 2>&1)
    # Determine whether the current version of rocprof-compute profile supports filtering by metric IDs or only by hardware blocks.
    declare -a profile_filter_arguments=()
    if printf '%s\n' "$profile_help" | grep -q 'metric-id'; then
        profile_filter_arguments=(
            -b
            "${_metrics_set[@]}"
        )

        echo "AMD profile filter mode: metric IDs"
    else
        profile_filter_arguments=(
            -b
            "${_profile_blocks_set[@]}"
        )

        echo "AMD profile filter mode: hardware blocks"
        echo "Required AMD hardware blocks: ${_profile_blocks_set[*]}"
    fi


    # creating profiling data
    rm -rf "workloads/$executable_filename" # Clear possible previous workloads folder TODO: Can be uncommented when not debugging
    rocprof-compute profile --name "$executable_filename" --no-roof --quiet "${profile_filter_arguments[@]}" -- "$executable" "$args"

    gpu_name=$(ls "workloads/$executable_filename/")
    # get the number of kernels and their respective kernel names in the executable
    analysis_output=$(rocprof-compute analyze -p "workloads/$executable_filename/$gpu_name/" --list-stats)

    #  Depending on the ROCm compiler/profiler version, rocprof-compute --list-stats may report an AMDHSA kernel-descriptor symbol whose demangled name ends with"[clone .kd]". 
    #  Parse the complete Kernel_Name table cell instead of assuming that the kernel name ends with ")". see https://llvm.org/docs/AMDGPUUsage.html?#amdhsa-kernel-name
    printf '%s\n' "$analysis_output" |
        perl -ne '
            if (/^\s*Detected Kernels\b/) {
                $in_kernel_table = 1;
                next;
            }

            if ($in_kernel_table && /^\s*╘/) {
                $in_kernel_table = 0;
                next;
            }

            if ($in_kernel_table && /^\s*│\s*(\d+)\s*│\s*([^│]+?)\s*│\s*$/) {
                print "$1,$2\n";
            } 
            ' > metrics/kernel_list.csv

    if [ ! -s metrics/kernel_list.csv ]; then
        echo "ERROR: Failed to extract kernels from rocprof-compute --list-stats."
        exit 1
    fi

    # Need to move everything into metrics folder because the analyze mode cant save the result in a directory
    # and also cant access parent directories
    mv "workloads" "metrics/workloads"
    cd metrics || exit

    # Determine if the current version of rocprof-compute produces legacy analyze output (version 3.0.0) or newer output formats.
    rocprof_compute_version_output=$(rocprof-compute --version 2>&1)
    case "$rocprof_compute_version_output" in
        *"rocprofiler-compute version: 3.0.0"*)
            legacy_analyze_output=true
            ;;
        *)
            legacy_analyze_output=false
            ;;
    esac
    printf 'Use legacy analyze output: %s\n' "$legacy_analyze_output"

    # Use different file descriptor (3) for the loop because rocprof-compute consumes/reads stdin resulting in only one kernel analyzed
    exec 3< kernel_list.csv

    # analyze each kernel separately
    while IFS=, read -r -u 3 kernel_number raw_kernel_name; do
        # Remove an optional AMDHSA descriptor suffix from the user-facing name.
        display_kernel_name=$(printf '%s' "$raw_kernel_name" | sed 's/[[:space:]]*\[clone \.kd\][[:space:]]*$//')

        # Replace spaces and special characters with underscores.
        sanitized_kernel_name=$(printf '%s' "$display_kernel_name" | tr -c 'a-zA-Z0-9' '_' | tr -s '_' | sed 's/^_*//;s/_*$//')

        output_file="${executable_filename}_${sanitized_kernel_name}_metrics"

        analyze_arguments=(
            analyze
            -p "workloads/$executable_filename/$gpu_name"
            -b
            "${_metrics_set[@]}"
            -n per_kernel
            -k "$kernel_number"
        )

        if [ "$legacy_analyze_output" = true ]; then
            # rocprofiler-compute 3.0.0 prints the report to stdout.
            rocprof-compute "${analyze_arguments[@]}" > "${output_file}.txt"
        else
            # Newer versions can create and name the text report themselves.
            rocprof-compute "${analyze_arguments[@]}" \
                --output-name "$output_file" \
                --output-format txt \
                > /dev/null
        fi
    done

    end_metrics=$(date +%s.%N)
    metrics_time=$(awk "BEGIN {print $end_metrics - $start_metrics}")
    exec 3<&- # release file descriptor 3
    cd .. || exit # go back to previous work directory
  else 
    echo "Skipping AMD metrics collection: selected analyses do not require AMD metrics."
    metrics_time=0
  fi



  ##### Creating file containing PC sampling data when supported by the gpu TODO Could be moved into metrics collection when pc sampling works without problems #####
  stochastic_gpus=$(rocprofv3 -L | grep -A 7 "GPU\s*:" | grep  "Method\s*:\s*stochastic")
  stochastic_gpus="" # TODO remove when rocprof-compute bug is fixed - doesnt collect data right now and data fields are just empty
  if [ -n "$stochastic_gpus" ]; then
      echo "==== collecting PC sampling data"
    
      start_pcsampling=$(date +%s.%N)
      mkdir pc_samples
      # Collect pc sampling data with the command from the docs - 128 cycles because nvidia version uses the same amount
      rocprof-compute profile -n pc_test -b 21 --no-roof --pc-sampling-method stochastic --pc-sampling-interval 128 -VVV -- "$executable" "$args"
      mv "workloads" "pc_samples/workloads"
      cd pc_samples || exit

      # Use different file descriptor (3) for the loop because rocprof-compute consumes/reads stdin resulting in only one kernel analyzed
      exec 3< ../metrics/kernel_list.csv
      # analyze each kernel separately
      while IFS=, read -r -u 3 kernel_number kernel_name; do
          # replace spaces and special characters in kernel_name for the output filename
          sanitized_kernel_name=$(printf '%s' "$kernel_name" | tr -c 'a-zA-Z0-9' '_' | sed 's/^_//;s/_$//')
          output_file="${executable_filename}_${sanitized_kernel_name}_pc_samples"

          # execute the per-kernel analysis
          rocprof-compute analyze -p "workloads/$executable_filename/$gpu_name" -b 21 -k "$kernel_number" \
          --output-name "$output_file" --output-format txt --pc-sampling-sorting-type offset
      done
      exec 3<&- # release file descriptor 3
      end_pcsampling=$(date +%s.%N)
      pcsampling_time=$(awk "BEGIN {print $end_pcsampling - $start_pcsampling}")
      cd .. || exit
  else
      pcsampling_time=0
      echo "==== no GPU on this system supports hardware-based (stochastic) PC sampling"
  fi
fi

#### Perform analysis on the collected data ####
cd "${gpuscout_dir}"/analysis_amd || exit

assembly="${gpuscout_tmp_dir}/${executable_filename}.s"
metrics_dir="${gpuscout_tmp_dir}/metrics"
livereg_dir="${gpuscout_tmp_dir}/livereg"

args_register_spilling=("${assembly}" "${metrics_dir}" "${livereg_dir}" "${json}" "${gpuscout_output_dir}")
args_restrict=("${assembly}" "${metrics_dir}" "${livereg_dir}" "${json}" "${gpuscout_output_dir}")
args_vectorized_load=("${assembly}" "${metrics_dir}" "${livereg_dir}" "${json}" "${gpuscout_output_dir}")
args_atomic_instruction=("${assembly}" "${metrics_dir}" "${json}" "${gpuscout_output_dir}")
args_wavefront_divergence=("${assembly}" "${metrics_dir}" "${json}" "${gpuscout_output_dir}")
args_shared_memory=("${assembly}" "${metrics_dir}" "${json}" "${gpuscout_output_dir}")
args_datatype_conversion=("${assembly}" "${metrics_dir}" "${json}" "${gpuscout_output_dir}")
args_deadlock_detection=("${assembly}" "${json}" "${gpuscout_output_dir}")

start_analysis=$(date +%s.%N)

if [ "$performance_mode" = false ]; then
  timed_run() {
    local analysis="$1"
    local binary="./analysis_${analysis}"
    local array_name="args_${analysis}"

    if [ ! -x "$binary" ]; then
        echo "ERROR: Unknown or unavailable AMD analysis binary: $binary" >&2
        return 1
    fi

    if ! declare -p "$array_name" &>/dev/null; then
        echo "ERROR: No argument array defined for AMD analysis: $analysis" >&2
        return 1
    fi

    local -n current_args="$array_name"

    t0=$(date +%s.%N)
    "$binary" "${current_args[@]}" # Execute the analysis binary with its arguments
    t1=$(date +%s.%N)
    dt=$(awk "BEGIN {print $t1 - $t0}")
    echo "Time for $analysis: ${dt}s"
  }
  for analysis in "${enabled_analyses[@]}"; do
    if ! timed_run "$analysis"; then
            echo "ERROR: AMD analysis failed: $analysis" >&2
            exit 1
        fi
    done
else
  # Use Multi-Threading for faster analysis -> each analysis within its own thread
  analysis_logs_dir="${gpuscout_tmp_dir}/analysis_tmp_outputs"
  mkdir -p "$analysis_logs_dir"
  declare -a names=() pids=()

  all_log="${analysis_logs_dir}/all_analyses.log"
  : >"$all_log"

  run() {
    local name="$1"; shift
    (
      "$@" # Execute the passed command
      rc=$? # Captures the exit code
      exit "$rc"
    ) >>"$all_log" 2>&1 &
    pids+=("$!")
  }

  # Launch all analyses in parallel
  run register_spilling      ./analysis_register_spilling  "$assembly" "$metrics_dir" "$livereg_dir" "$json" "$gpuscout_output_dir"
  run restrict               ./analysis_restrict           "$assembly" "$metrics_dir" "$livereg_dir" "$json" "$gpuscout_output_dir"
  run vectorized_load        ./analysis_vectorized_load    "$assembly" "$metrics_dir" "$livereg_dir" "$json" "$gpuscout_output_dir"
  run atomic_instruction     ./analysis_atomic_instruction "$assembly" "$metrics_dir" "$json" "$gpuscout_output_dir"
  run wavefront_divergence   ./analysis_wavefront_divergence "$assembly" "$metrics_dir" "$json" "$gpuscout_output_dir"
  run shared_memory          ./analysis_shared_memory      "$assembly" "$metrics_dir" "$json" "$gpuscout_output_dir"
  run datatype_conversion    ./analysis_datatype_conversion "$assembly" "$metrics_dir" "$json" "$gpuscout_output_dir"
  run deadlock_detection     ./analysis_deadlock_detection "$assembly" "$json" "$gpuscout_output_dir"

  # Wait and collect exit codes
  declare -a rc=()
  for i in "${!pids[@]}"; do
    if wait "${pids[$i]}"; then
      rc[$i]=0
    else
      rc[$i]=$?
    fi
  done

  # Print captured outputs after all are done
  cat "$all_log"

fi


# output all used files in JSON format
if [ "$json" = true ]; then

    echo "======================================================================================================"
    echo "==== generating JSON output"
    # ./save_to_json ${gpuscout_output_dir} ${gpuscout_tmp_dir}/result-${run_prefix} ${gpuscout_tmp_dir}/nvdisasm-executable-${executable_filename}-sass.txt ${gpuscout_tmp_dir}/nvdisasm-registers-executable-${executable_filename}-sass.txt ${gpuscout_tmp_dir}/nvdisasm-executable-${executable_filename}-ptx.txt ${gpuscout_tmp_dir}/pcsampling_${executable_filename}.txt
    ./save_to_json ${gpuscout_output_dir} ${gpuscout_tmp_dir}/result-${run_prefix} "${assembly}" "${metrics_dir}" "$livereg_dir"
fi

end_analysis=$(date +%s.%N)
analysis_time=$(awk "BEGIN {print $end_analysis - $start_analysis}")

echo "======================================================================================================"
echo "Time for Static Code Analysis: ${static_time}s"
if [ "$dry_run" = false ]; then
    echo "Time for PC Sampling:          ${pcsampling_time}s"
    echo "Time for Metrics Collection:   ${metrics_time}s"
fi
echo "Time for Merging Analysis:     ${analysis_time}s"
echo "======================================================================================================"

cd ..
