#ifndef PARSER_METRICS_HPP
#define PARSER_METRICS_HPP

#include <unordered_map>
#include <filesystem>
#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <tuple>
#include <regex>
#include "../utilities/json.hpp"
#include "amdgcn_instructions.hpp"
#include "../utilities/helper.hpp"

using json = nlohmann::json;
namespace fs = std::filesystem;

std::regex line_pattern(std::string id)
{
    return std::regex(
        "^│"
        "\\s*"
        + id +
        "\\s*│"
        "\\s*([\\/\\s\\w\\.\\(\\)\\-]+)\\s*│"
        "\\s*([\\/\\s\\w\\.\\(\\)\\-]+)\\s*│"
        "(?:\\s*([\\/\\s\\w\\.\\(\\)\\-]+)\\s*│)?"
        "(?:\\s*([\\/\\s\\w\\.\\(\\)\\-]+)\\s*│)?"
        "(?:\\s*([\\/\\s\\w\\.\\(\\)\\-]+)\\s*│)?"
        "(?:\\s*([\\/\\s\\w\\.\\(\\)\\-]+)\\s*│)?"
        "(?:\\s*([\\/\\s\\w\\.\\(\\)\\-]+)\\s*│)?"
    );
}

std::regex kernel_name_pattern() {
    /*
        ╒═════════╤════════════════════════════════════════╤═════════╤═══════════╤════════════╤══════════════╤═══════╤═════╕
        │   index │ Kernel_Name                            │   Count │   Sum(ns) │   Mean(ns) │   Median(ns) │   Pct │ S   │
        ╞═════════╪════════════════════════════════════════╪═════════╪═══════════╪════════════╪══════════════╪═══════╪═════╡
        │       0 │ __amd_rocclr_copyBuffer                │    5.00 │  29206.50 │    5841.30 │      5083.00 │ 42.80 │     │
        ...
        ├─────────┼────────────────────────────────────────┼─────────┼───────────┼────────────┼──────────────┼───────┼─────┤
        │       3 │ spillingKernel(float*, float*, float*) │    1.00 │   7815.00 │    7815.00 │      7815.00 │ 11.45 │ *   │
     */
    return std::regex(
        "^│" // left border
        "\\s*" // whitespaces after border
        "\\d*" // kernel number
        "\\s*│" // whitespaces after id and border
        "\\s*(.*\\))\\s*│" // Kernel name
        "[^│]*│" // Count segment
        "[^│]*│" // Sum segment
        "[^│]*│" // Mean segment
        "[^│]*│" // Median segment
        "[^│]*│" // Pct segment
        "\\s*\\*\\s*│" // Selected kernel shown through *
        "\\s*" // whitespaces at the end
    );
}

/// @brief metric data to collect from rocprofiler compute
struct mtc
{
    double ID_7_2_4;
    double ID_10_1_6;
    double ID_10_2_14;
    double ID_11_2_5;
    double ID_12_1_0;
    double ID_12_1_1;
    double ID_12_1_3;
    double ID_12_2_5;
    double ID_15_1_9;
    double ID_15_1_13;
    double ID_16_3_3;
    double ID_16_3_5;
    double ID_17_2_7;
    double ID_17_3_1;
    double ID_17_3_4;
    double ID_17_5_10;
};

// Defines which metrics are stored in the json result TODO
NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(mtc,
    ID_7_2_4,
    ID_10_1_6,
    ID_10_2_14,
    ID_11_2_5,
    ID_12_1_0,
    ID_12_1_1,
    ID_12_1_3,
    ID_12_2_5,
    ID_15_1_9,
    ID_15_1_13,
    ID_16_3_3,
    ID_16_3_5,
    ID_17_2_7,
    ID_17_3_1,
    ID_17_3_4,
    ID_17_5_10
)


/// @brief  parse the metric file generated by rocprofiler compute
/// @param  directory containing metrics files
/// @param  object file for matching mangled kernel names
/// @return metric values for each kernel
std::unordered_map<std::string, mtc> parser_metrics(const std::string &dir, const std::string &assembly_filename)
{
    std::unordered_map<std::string, mtc> mtc_map;

    // Build mangled kernel name lookup table - rocprof-compute cant provide this
    // Because of this the mangled kernel name is taken out of the object file
    std::unordered_map<std::string, std::string> kernel_names_table;
    std::fstream as_file(assembly_filename, std::ios::in);
    std::string as_line; // stores the current line in the assembly file
    int instr_counter;
    if (as_file.is_open()) {
        while (std::getline(as_file, as_line)) {
            std::smatch match;

            // Line matches kernel
            if (std::regex_search(as_line, match, regex_krn_name)) {
                std::string demangled_krn_name = get_demangled_kernel(match[1], "c++filt");

                if (kernel_names_table.find(demangled_krn_name) == kernel_names_table.end()) {
                    kernel_names_table[demangled_krn_name] = match[1];
                }
            }
        }
    }

     
    // Iterate over files in the given metrics folder
    for (const auto& entry : fs::directory_iterator(dir))
    {
	// check if the current entry is a file
        if (fs::is_regular_file(entry.status())) 
	    {
            std::string filename = entry.path().filename().string();

            // regular expression to match files ending with _<kernel_name>_metrics.txt
            std::regex file_pattern(".*_([\\w]+)_metrics\\.txt$");
            std::smatch file_match;

            if (std::regex_match(filename, file_match, file_pattern)) 
	        {
                mtc mtc_obj = {0}; // zero initialized to prevent undefined behaviour
                std::string krn_name = "ERROR"; // No error catching needed because metrics wont be added when no krn_name was set
                bool krn_name_set = false;
                std::ifstream file(entry.path());

                if (file.is_open()) 
		        {
                    std::string line;
                    while (std::getline(file, line)) 
		            {
			            std::smatch line_match;
                        // Kernel name parsing - only needed once per metrics file
                        if (krn_name_set == false) {
                            if (std::regex_match(line, line_match, kernel_name_pattern())) {
                                krn_name = kernel_names_table[line_match[1].str()];
                                krn_name_set = true;
                            }
                            else {
                                continue;
                            }
                        }


                        // Metrics parsing
                        if(std::regex_search(line, line_match, line_pattern("7\\.2\\.4")))
                        {
                            mtc_obj.ID_7_2_4 = line_match[2].str() == " " ? 0 : std::stod(line_match[2].str());
                        }
                        if(std::regex_search(line, line_match, line_pattern("10\\.1\\.6")))
                        {
                            mtc_obj.ID_10_1_6 = line_match[2].str() == " " ? 0 : std::stod(line_match[2].str());
                        }
                        if(std::regex_search(line, line_match, line_pattern("10\\.2\\.14")))
                        {
                            mtc_obj.ID_10_2_14 = line_match[2].str() == " " ? 0 : std::stod(line_match[2].str());
                        }
                        if(std::regex_search(line, line_match, line_pattern("11\\.2\\.5")))
                        {
                            mtc_obj.ID_11_2_5 = line_match[2].str() == " " ? 0 : std::stod(line_match[2].str());
                        }
                        if(std::regex_search(line, line_match, line_pattern("12\\.1\\.0")))
                        {
                            mtc_obj.ID_12_1_0 = line_match[2].str() == " " ? 0 : std::stod(line_match[2].str());
                        }
                        if(std::regex_search(line, line_match, line_pattern("12\\.1\\.1")))
                        {
                            mtc_obj.ID_12_1_1 = line_match[2].str() == " " ? 0 : std::stod(line_match[2].str());
                        }
                        if(std::regex_search(line, line_match, line_pattern("12\\.1\\.3")))
                        {
                            mtc_obj.ID_12_1_3 = line_match[2].str() == " " ? 0 : std::stod(line_match[2].str());
                        }
                        if(std::regex_search(line, line_match, line_pattern("12\\.2\\.5")))
                        {
                            mtc_obj.ID_12_2_5 = line_match[2].str() == " " ? 0 : std::stod(line_match[2].str());
                        }
                        if(std::regex_search(line, line_match, line_pattern("15\\.1\\.9")))
                        {
                            mtc_obj.ID_15_1_9 = line_match[2].str() == " " ? 0 : std::stod(line_match[2].str());
                        }
                        if(std::regex_search(line, line_match, line_pattern("15\\.1\\.13")))
                        {
                            mtc_obj.ID_15_1_13 = line_match[2].str() == " " ? 0 : std::stod(line_match[2].str());
                        }
                        if(std::regex_search(line, line_match, line_pattern("16\\.3\\.3")))
                        {
                            mtc_obj.ID_16_3_3 = line_match[2].str() == " " ? 0 : std::stod(line_match[2].str());
                        }
                        if(std::regex_search(line, line_match, line_pattern("16\\.3\\.5")))
                        {
                            mtc_obj.ID_16_3_5 = line_match[2].str() == " " ? 0 : std::stod(line_match[2].str());
                        }
                        if(std::regex_search(line, line_match, line_pattern("17\\.2\\.7")))
                        {
                            mtc_obj.ID_17_2_7 = line_match[2].str() == " " ? 0 : std::stod(line_match[2].str());
                        }
                        if(std::regex_search(line, line_match, line_pattern("17\\.3\\.1")))
                        {
                            mtc_obj.ID_17_3_1 = line_match[2].str() == " " ? 0 : std::stod(line_match[2].str());
                        }
                        if(std::regex_search(line, line_match, line_pattern("17\\.3\\.4")))
                        {
                            mtc_obj.ID_17_3_4 = line_match[2].str() == " " ? 0 : std::stod(line_match[2].str());
                        }
                        if(std::regex_search(line, line_match, line_pattern("17\\.5\\.10")))
                        {
                            mtc_obj.ID_17_5_10 = line_match[2].str() == " " ? 0 : std::stod(line_match[2].str());
                        }
                    }
                    file.close();

                    mtc_map[krn_name] = mtc_obj;
                }
                else
                {
                    std::cout << "Error :: Could not open the file: " << filename << std::endl;
                }
            }
        }
    }
    return mtc_map;
}

#endif // PARSER_METRICS_HPP
