#ifndef PARSER_METRICS_HPP
#define PARSER_METRICS_HPP

#include <unordered_map>
#include <filesystem>
#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <tuple>
#include <regex>
#include "../utilities/json.hpp"
#include "amdgcn_instructions.hpp"
#include "../utilities/helper.hpp"
#include "amd_helper.hpp"

using json = nlohmann::json;
namespace fs = std::filesystem;

// Used for matching the individual metrics line
std::regex line_pattern(std::string id)
{
    /*
    * ╒═════════════╤════════════════════════╤═══════════╤═══════════╤═══════════╤═══════════════════╕
    * │ Metric_ID   │ Metric                 │       Avg │       Min │       Max │ Unit              │
    * ╞═════════════╪════════════════════════╪═══════════╪═══════════╪═══════════╪═══════════════════╡
    * │ 7.2.4       │ Dependency Wait Cycles │ 672972.00 │ 672972.00 │ 672972.00 │ Cycles per kernel │
    * ╘═════════════╧════════════════════════╧═══════════╧═══════════╧═══════════╧═══════════════════╛
    */
    return std::regex(
        "^│"                                     // left border
        "\\s*"                                      // whitespaces after border
        + id +                                      // id=7.2.4
        "\\s*│"                                     // whitespaces after id
        "\\s*([\\/\\s\\w\\.\\(\\)\\-]+)\\s*│"       // Metric type e.g Dependency Wait Cycles
        "\\s*([\\/\\s\\w\\.\\(\\)\\-]+)\\s*│"
        "(?:\\s*([\\/\\s\\w\\.\\(\\)\\-]+)\\s*│)?"
        "(?:\\s*([\\/\\s\\w\\.\\(\\)\\-]+)\\s*│)?"
        "(?:\\s*([\\/\\s\\w\\.\\(\\)\\-]+)\\s*│)?"
        "(?:\\s*([\\/\\s\\w\\.\\(\\)\\-]+)\\s*│)?"
        "(?:\\s*([\\/\\s\\w\\.\\(\\)\\-]+)\\s*│)?"
    );
}


/// @brief metric data to collect from rocprofiler compute
struct mtc
{
    double ID_7_2_4;
    double ID_10_1_6;
    double ID_10_2_14;
    double ID_11_2_5;
    double ID_12_1_0;
    double ID_12_1_1;
    double ID_12_1_3;
    double ID_12_2_5;
    double ID_15_1_9;
    double ID_15_1_13;
    double ID_16_3_3;
    double ID_16_3_5;
    double ID_17_2_7;
    double ID_17_3_1;
    double ID_17_3_4;
    double ID_17_5_10;
};

// Defines which metrics are stored in the json result
NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(mtc,
    ID_7_2_4,
    ID_10_1_6,
    ID_10_2_14,
    ID_11_2_5,
    ID_12_1_0,
    ID_12_1_1,
    ID_12_1_3,
    ID_12_2_5,
    ID_15_1_9,
    ID_15_1_13,
    ID_16_3_3,
    ID_16_3_5,
    ID_17_2_7,
    ID_17_3_1,
    ID_17_3_4,
    ID_17_5_10
)


/// @brief  parse the metric file generated by rocprofiler compute
/// @param  directory containing metrics files
/// @param  object file for matching mangled kernel names
/// @return metric values for each kernel
std::unordered_map<std::string, mtc> parser_metrics(const std::string &dir, const std::string &assembly_filename)
{
    std::unordered_map<std::string, mtc> mtc_map;

    // Build mangled kernel name lookup table - rocprof-compute cant provide this
    std::unordered_map<std::string, std::string> kernel_names_table = build_kernel_names_table(assembly_filename);

     
    // Iterate over files in the given metrics folder
    for (const auto& entry : fs::directory_iterator(dir))
    {
	// check if the current entry is a file
        if (fs::is_regular_file(entry.status())) 
	    {
            std::string filename = entry.path().filename().string();

            // regular expression to match files ending with _<kernel_name>_metrics.txt
            std::regex file_pattern(".*_([\\w]+)_metrics\\.txt$");
            std::smatch file_match;

            if (std::regex_match(filename, file_match, file_pattern)) 
	        {
                mtc mtc_obj = {0}; // zero initialized to prevent undefined behaviour
                std::string krn_name = "ERROR"; // No error catching needed because metrics wont be added when no krn_name was set
                bool krn_name_set = false;
                std::ifstream file(entry.path());

                if (file.is_open()) 
		        {
                    std::string line;

                    // Iterate through file
                    while (std::getline(file, line)) 
		            {
			            std::smatch line_match;
                        // Kernel name parsing - only needed once per metrics file
                        if (krn_name_set == false) {
                            if (std::regex_search(line, line_match, kernel_name_pattern())) {
                                krn_name = kernel_names_table[line_match[1].str()];
                                krn_name_set = true;
                            }
                            else {
                                continue;
                            }
                        }


                        // Metrics parsing
                        if(std::regex_search(line, line_match, line_pattern("7\\.2\\.4")))
                        {
                            mtc_obj.ID_7_2_4 = line_match[2].str() == " " ? 0 : std::stod(line_match[2].str());
                        }
                        if(std::regex_search(line, line_match, line_pattern("10\\.1\\.6")))
                        {
                            mtc_obj.ID_10_1_6 = line_match[2].str() == " " ? 0 : std::stod(line_match[2].str());
                        }
                        if(std::regex_search(line, line_match, line_pattern("10\\.2\\.14")))
                        {
                            mtc_obj.ID_10_2_14 = line_match[2].str() == " " ? 0 : std::stod(line_match[2].str());
                        }
                        if(std::regex_search(line, line_match, line_pattern("11\\.2\\.5")))
                        {
                            mtc_obj.ID_11_2_5 = line_match[2].str() == " " ? 0 : std::stod(line_match[2].str());
                        }
                        if(std::regex_search(line, line_match, line_pattern("12\\.1\\.0")))
                        {
                            mtc_obj.ID_12_1_0 = line_match[2].str() == " " ? 0 : std::stod(line_match[2].str());
                        }
                        if(std::regex_search(line, line_match, line_pattern("12\\.1\\.1")))
                        {
                            mtc_obj.ID_12_1_1 = line_match[2].str() == " " ? 0 : std::stod(line_match[2].str());
                        }
                        if(std::regex_search(line, line_match, line_pattern("12\\.1\\.3")))
                        {
                            mtc_obj.ID_12_1_3 = line_match[2].str() == " " ? 0 : std::stod(line_match[2].str());
                        }
                        if(std::regex_search(line, line_match, line_pattern("12\\.2\\.5")))
                        {
                            mtc_obj.ID_12_2_5 = line_match[2].str() == " " ? 0 : std::stod(line_match[2].str());
                        }
                        if(std::regex_search(line, line_match, line_pattern("15\\.1\\.9")))
                        {
                            mtc_obj.ID_15_1_9 = line_match[2].str() == " " ? 0 : std::stod(line_match[2].str());
                        }
                        if(std::regex_search(line, line_match, line_pattern("15\\.1\\.13")))
                        {
                            mtc_obj.ID_15_1_13 = line_match[2].str() == " " ? 0 : std::stod(line_match[2].str());
                        }
                        if(std::regex_search(line, line_match, line_pattern("16\\.3\\.3")))
                        {
                            mtc_obj.ID_16_3_3 = line_match[2].str() == " " ? 0 : std::stod(line_match[2].str());
                        }
                        if(std::regex_search(line, line_match, line_pattern("16\\.3\\.5")))
                        {
                            mtc_obj.ID_16_3_5 = line_match[2].str() == " " ? 0 : std::stod(line_match[2].str());
                        }
                        if(std::regex_search(line, line_match, line_pattern("17\\.2\\.7")))
                        {
                            mtc_obj.ID_17_2_7 = line_match[2].str() == " " ? 0 : std::stod(line_match[2].str());
                        }
                        if(std::regex_search(line, line_match, line_pattern("17\\.3\\.1")))
                        {
                            mtc_obj.ID_17_3_1 = line_match[2].str() == " " ? 0 : std::stod(line_match[2].str());
                        }
                        if(std::regex_search(line, line_match, line_pattern("17\\.3\\.4")))
                        {
                            mtc_obj.ID_17_3_4 = line_match[2].str() == " " ? 0 : std::stod(line_match[2].str());
                        }
                        if(std::regex_search(line, line_match, line_pattern("17\\.5\\.10")))
                        {
                            mtc_obj.ID_17_5_10 = line_match[2].str() == " " ? 0 : std::stod(line_match[2].str());
                        }
                    }
                    file.close();

                    mtc_map[krn_name] = mtc_obj;
                }
                else
                {
                    std::cout << "Error :: Could not open the file: " << filename << std::endl;
                }
            }
        }
    }
    return mtc_map;
}

json total_memory_flow(const std::unordered_map<std::string, mtc> &all_metrics/*, int total_SM*/) {
    // TODO select the to be included metrics for the total memory flow metrics
    return {
        {"general", {
            {"total_instructions", all_metrics}, // TODO update with real metrics
            //{"l2_queries", total_l2_queries},
            //{"l2_cache_hit_perc", all_metrics.metrics_list.lts__t_sector_hit_rate},
            //{"loads_l2_cache_hit_perc", all_metrics.metrics_list.lts__t_sector_op_read_hit_rate},
            ////{"stores_l2_cache_hit_perc", all_metrics.metrics_list.lts__t_sector_op_write_hit_rate},
            //{"loads_l2_to_dram_bytes", loads_l2_to_dram_bytes},
            //{"stores_l2_to_dram_bytes", stores_l2_to_dram_bytes},
        }},
        /*
        {"global", {
            {"instructions", all_metrics.metrics_list.sm__sass_inst_executed_op_global_ld + all_metrics.metrics_list.sm__sass_inst_executed_op_global_st},
            {"bytes_per_instruction", global_data_per_instr_bytes},

            {"loads_instructions", all_metrics.metrics_list.sm__sass_inst_executed_op_global_ld},
            {"loads_to_l1_bytes", 32 * all_metrics.metrics_list.l1tex__t_sectors_pipe_lsu_mem_global_op_ld},
            {"loads_l1_cache_hit_perc", all_metrics.metrics_list.l1tex__t_sector_pipe_lsu_mem_global_op_ld_hit_rate},
            {"loads_l1_to_l2_bytes", global_loads_l1_to_l2_bytes},

            {"stores_instructions", all_metrics.metrics_list.sm__sass_inst_executed_op_global_st},
            {"stores_to_l1_bytes", 32 * all_metrics.metrics_list.l1tex__t_sectors_pipe_lsu_mem_global_op_st},
            {"stores_l1_cache_hit_perc", all_metrics.metrics_list.l1tex__t_sector_pipe_lsu_mem_global_op_st_hit_rate},
            {"stores_l1_to_l2_bytes", global_stores_l1_to_l2_bytes},

            {"atomic_to_l1_bytes", global_atomics_to_l1_bytes},
            {"atomic_l1_cache_hit_perc", global_atomics_l1_cache_hit_perc},
            {"atomics_l1_to_l2_bytes", global_atomics_l1_to_l2_bytes},
            {"atomics_l2_cache_hit_perc", global_atomics_l2_cache_hit_perc},
            {"atomics_l2_to_dram_bytes", global_atomics_l2_to_dram_bytes},
        }},
        {"local", {
            {"instructions", all_metrics.metrics_list.sm__sass_inst_executed_op_local_ld + all_metrics.metrics_list.sm__sass_inst_executed_op_local_st},
            {"l2_queries_perc", l2_queries_lmem_percent},

            {"loads_instructions", all_metrics.metrics_list.sm__sass_inst_executed_op_local_ld},
            {"loads_to_l1_bytes", 32 * all_metrics.metrics_list.l1tex__t_sectors_pipe_lsu_mem_local_op_ld},
            {"loads_l1_cache_hit_perc", all_metrics.metrics_list.l1tex__t_sector_pipe_lsu_mem_local_op_ld_hit_rate},
            {"loads_l1_to_l2_bytes", local_loads_l1_to_l2_bytes},

            {"stores_instructions", all_metrics.metrics_list.sm__sass_inst_executed_op_local_st},
            {"stores_to_l1_bytes", 32 * all_metrics.metrics_list.l1tex__t_sectors_pipe_lsu_mem_local_op_st},
            {"stores_l1_cache_hit_perc", all_metrics.metrics_list.l1tex__t_sector_pipe_lsu_mem_local_op_st_hit_rate},
            {"stores_l1_to_l2_bytes", local_stores_l1_to_l2_bytes},
        }},
        {"shared", {
            {"instructions", all_metrics.metrics_list.sm__sass_inst_executed_op_shared_ld + all_metrics.metrics_list.sm__sass_inst_executed_op_shared_st},

            {"loads_instructions", all_metrics.metrics_list.sm__sass_inst_executed_op_shared_ld},
            {"loads_efficiency_perc", all_metrics.metrics_list.smsp__sass_average_data_bytes_per_wavefront_mem_shared_op_ld},
            {"loads_bank_conflict", shared_bank_conflict},

            {"stores_instructions", all_metrics.metrics_list.sm__sass_inst_executed_op_shared_st},
            {"ldgsts_instructions", all_metrics.metrics_list.smsp__inst_executed_op_ldgsts}
        }},
        {"texture", {
            {"instructions", all_metrics.metrics_list.sm__sass_inst_executed_op_texture},
            {"loads_to_l1_bytes", all_metrics.metrics_list.l1tex__t_sectors_pipe_tex_mem_texture},
            {"loads_l1_cache_hit_perc", all_metrics.metrics_list.l1tex__t_sector_pipe_tex_mem_texture_op_tex_hit_rate},
            {"loads_l1_to_l2_bytes", texture_loads_l1_to_l2_bytes},
            {"loads_l2_to_dram_bytes", texture_loads_l2_to_dram_bytes},
        }}
        */
    };
}

#endif // PARSER_METRICS_HPP